[buildPlans.IosevkaMuse]
family = "Iosevka Muse"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.IosevkaMuse.variants]
  inherits = "ss20"

    [buildPlans.IosevkaMuse.variants.design]
    seven = "bend-serifless-crossbar"
    zero = "dotted"
    capital-g = "toothless-corner-serifless-hooked"
    capital-j = "serifless"
    capital-q = "crossing-curly-tailed"
    capital-z = "curly-serifless-with-crossbar"
    a = "double-storey-toothless-corner"
    b = "toothless-corner-serifless"
    d = "toothless-rounded-serifless"
    # f = "flat-hook"
    g = "single-storey-earless-corner"
    i = "tailed"
    j = "serifless"
    k = "curly-serifless"
    l = "tailed"
    m = "earless-corner-double-arch-serifless"
    n = "earless-corner-straight-serifless"
    p = "earless-corner-serifless"
    q = "earless-corner-diagonal-tailed-serifless"
    r = "earless-corner-serifless"
    t = "bent-hook-asymmetric"
    u = "toothless-corner-serifless"
    y = "cursive-serifless"
    z = "curly-serifless-with-crossbar"
    lower-iota = "tailed"
    lower-xi = "rounded"
    cyrl-yeri = "round"
    cyrl-yery = "round-tailed"
    cyrl-capital-ya = "curly-serifless"
    cyrl-ya = "curly-serifless"
    asterisk = "penta-low"
    brace = "straight"
    guillemet = "straight"
    at = "fourfold-solid-inner"
    dollar = "open"
    percent = "rings-continuous-slash"
    micro-sign = "toothless-corner-serifless"

  [buildPlans.IosevkaMuse.ligations]
  inherits = "dlig"

[buildPlans.IosevkaMuse.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaMuse.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.IosevkaMuse.widths.Condensed]
shape = 416
menu = 3
css = "condensed"
